---
version: '2'
services:
  # Can't use service elasticsearch=<num> for now due to named volumes
  elasticsearch1:
  # Equivalent to:
  # docker run --rm --cap-add=IPC_LOCK --ulimit memlock=-1:-1 --ulimit nofile=65536:65536 -t -P --memory="4g" -e "discovery.zen.minimum_master_nodes=${ES_NODE_COUNT}" -v esdata:/usr/share/elasticsearch/data docker.elastic.co/elasticsearch/elasticsearch:5.0.0-rc1
    build:
      context: build/elasticsearch
      args:
        ELASTIC_VERSION: "${ELASTIC_VERSION}"
        ES_DOWNLOAD_URL: "${ES_DOWNLOAD_URL}"
        ES_JAVA_OPTS: "${ES_JAVA_OPTS}"
    cap_add:
      - IPC_LOCK
    environment:
      - discovery.zen.minimum_master_nodes=${ES_NODE_COUNT}
      - searchguard.ssl.transport.keystore_filepath=demo_certs/keystore.jks
      - searchguard.ssl.transport.truststore_filepath=demo_certs/truststore.jks
      - searchguard.ssl.transport.enforce_hostname_verification=false
      - searchguard.authcz.admin_dn.0=CN=kirk,OU=client,O=client,L=test,C=de  
    image: "${VERSIONED_IMAGE}"
    mem_limit: 4g
    networks:
      esnet:
        aliases:
          - elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - $PWD/demo_certs/:/usr/share/elasticsearch/config/demo_certs:ro
  elasticsearch2:
    build:
      context: build/elasticsearch
      args:
        ELASTIC_VERSION: "${ELASTIC_VERSION}"
        ES_DOWNLOAD_URL: "${ES_DOWNLOAD_URL}"
        ES_JAVA_OPTS: "${ES_JAVA_OPTS}"
    cap_add:
      - IPC_LOCK
    environment:
      - discovery.zen.ping.unicast.hosts=elasticsearch1
      - discovery.zen.minimum_master_nodes=${ES_NODE_COUNT}
      - searchguard.ssl.transport.keystore_filepath=demo_certs/keystore.jks
      - searchguard.ssl.transport.truststore_filepath=demo_certs/truststore.jks
      - searchguard.ssl.transport.enforce_hostname_verification=false
      - searchguard.authcz.admin_dn.0=CN=kirk,OU=client,O=client,L=test,C=de 
    image: "${VERSIONED_IMAGE}"
    mem_limit: 4g
    networks:
      - esnet
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata2:/usr/share/elasticsearch/data
      - $PWD/demo_certs/:/usr/share/elasticsearch/config/demo_certs:ro
  sgadmin:
    build:
      context: build/sgadmin
      args:
        ELASTIC_VERSION: "${ELASTIC_VERSION}"
        SG_VERSION: "${SG_VERSION}"
        ES_JAVA_OPTS: "${ES_JAVA_OPTS}"
    image: "${VERSIONED_IMAGE}-sgadmin"
    mem_limit: 128m
    networks:
      - esnet
    volumes:
      - $PWD/demo_certs/:/demo_certs:ro
    command: -ts /demo_certs/truststore.jks -ks /demo_certs/keystore.jks -h elasticsearch -nhnv -cn docker-cluster -cd /usr/share/sgadmin/sgconfig
    links:
      - elasticsearch1:elasticsearch
  tester:
    build:
      context: build/python
    command: py.test -p no:cacheprovider tests/
    image: "tester:latest"
    networks:
      - esnet
    links:
      - elasticsearch1:elasticsearch
    volumes:
      - $PWD/tests:/home/testuser/tests:ro
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
networks:
  esnet:
    driver: bridge
